package net.arunreddy.speechbrowser

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class SecurityFilters {
    def filters = {
        corpus(controller:"corpus", action:"*") {
            before = {
                accessControl { true }
            }
        }
        filebrowser(uri: "/fileServlet") {
            before = {
                // Access control by convention.
                accessControl()
            }
        }
    }
}
